#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
export IDF_PATH=../../
PROJECT_NAME := 1_take_pic_http_to_cloud

include $(IDF_PATH)/make/project.mk

